---
title: "Draft NEL WiLMS Data"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    source_code: embed
---

```{r setup, include=FALSE}
library(flexdashboard)

library(leaflet)
library(rgdal)

setwd("~/wilms_github/nel_wilms")

join<-read.csv("wiscland_join_info.csv",fileEncoding = 'UTF-8-BOM')

lake_join<-read.csv("lake_attributes.csv")

lake_additions<-readOGR(".","lake_additions")
lake_additions <- spTransform(lake_additions, CRS("+init=epsg:4326"))
lake_additions<-merge(lake_additions,lake_join,by="WBIC")

gass_hydro<-readOGR(".","gass_hydro")
gass_hydro <- spTransform(gass_hydro, CRS("+init=epsg:4326"))

questions<-readOGR(".","questions")
questions <- spTransform(questions, CRS("+init=epsg:4326"))

subbasin<-readOGR(".","subbasins")
subbasin <- spTransform(subbasin, CRS("+init=epsg:4326"))

cal_man_9KE<-readOGR(".","cal_man_9KE_onterra")
cal_man_9KE<- spTransform(cal_man_9KE, CRS("+init=epsg:4326"))

flow<-readOGR(".","flow")
flow <- spTransform(flow, CRS("+init=epsg:4326"))

buffer<-readOGR(".","laes_buffer")
buffer <- spTransform(buffer, CRS("+init=epsg:4326"))

manitowoc_co_lidar<-readOGR(".","manitowoc_co_lidar_lakes")
manitowoc_co_lidar <- spTransform(manitowoc_co_lidar, CRS("+init=epsg:4326"))

manitowoc_co_lidar_private<-readOGR(".","manitowoc_co_lidar_lakes_private")
manitowoc_co_lidar_private <- spTransform(manitowoc_co_lidar_private, CRS("+init=epsg:4326"))

nel_boundary<-readOGR(".","nel_boundary")
nel_boundary<- spTransform(nel_boundary, CRS("+init=epsg:4326"))

septic_parcel<-readOGR(".","septic_parcel_status")
septic_parcel <- spTransform(septic_parcel, CRS("+init=epsg:4326"))

septic_pts<-readOGR(".","septic_pts_status")
septic_pts <- spTransform(septic_pts, CRS("+init=epsg:4326"))

swat_routing<-readOGR(".","swat_routing")
swat_routing <- spTransform(swat_routing, CRS("+init=epsg:4326"))

wiscland_wilms<-readOGR(".","wiscland_wilms_less")
wiscland_wilms <- spTransform(wiscland_wilms, CRS("+init=epsg:4326"))
wiscland_wilms<-merge(wiscland_wilms,join,by="GRIDCODE")

wiscland_wilms_updates<-readOGR(".","wiscland_wilms_updates")
wiscland_wilms_updates<- spTransform(wiscland_wilms_updates, CRS("+init=epsg:4326"))

impaired_lakes<-readOGR(".","impaired_lakes_2020")
impaired_lakes<- spTransform(impaired_lakes, CRS("+init=epsg:4326"))
impaired_lakes<-merge(impaired_lakes,lake_join,by="WBIC")

impaired_streams<-readOGR(".","2018_2020_streams")
impaired_streams<- spTransform(impaired_streams, CRS("+init=epsg:4326"))


county<-readOGR(".","counties")
county<- spTransform(county, CRS("+init=epsg:4326"))
```

Column {data-width=650}
-----------------------------------------------------------------------


```{r, out.width='100%', out.height ='100%'}



#wiscland, color
color<-c(rgb(170,0,0,.5,maxColorValue=255),
         rgb(216,147,130,.5,maxColorValue=255),
         rgb(242,238,134,.5,maxColorValue=255),
         rgb(242,238,134,.5,maxColorValue=255),
         rgb(242,238,134,.5,maxColorValue=255),
         rgb(242,238,134,.5,maxColorValue=255),
         rgb(230,226,161,.5,maxColorValue=255),
         rgb(230,172,46,.5,maxColorValue=255),
         rgb(230,172,46,.5,maxColorValue=255),
         rgb(156,114,9,.5,maxColorValue=255),
         rgb(156,114,9,.5,maxColorValue=255),
         rgb(1,100,0,.5,maxColorValue=255),
         rgb(1,100,0,.5,maxColorValue=255),
         rgb(1,100,0,.5,maxColorValue=255),
         rgb(106,184,106,.5,maxColorValue=255),
         rgb(106,184,106,.5,maxColorValue=255),
         rgb(106,184,106,.5,maxColorValue=255),
         rgb(106,184,106,.5,maxColorValue=255),
         rgb(106,184,106,.5,maxColorValue=255),
         rgb(30,152,30,.5,maxColorValue=255),
         rgb(207,235,250,.5,maxColorValue=255),
         rgb(149,237,242,.5,maxColorValue=255),
         rgb(112,163,186,.5,maxColorValue=255),
         rgb(112,163,186,.5,maxColorValue=255),
         rgb(112,163,186,.5,maxColorValue=255),
         rgb(0,209,220,.5,maxColorValue=255),
         rgb(0,209,220,.5,maxColorValue=255),
         rgb(0,209,220,.5,maxColorValue=255),
         rgb(15,124,130,.5,maxColorValue=255),
         rgb(15,124,130,.5,maxColorValue=255),
         rgb(15,124,130,.5,maxColorValue=255),
         rgb(15,124,130,.5,maxColorValue=255),
         rgb(15,124,130,.5,maxColorValue=255),
         rgb(120,120,120,.5,maxColorValue=255),
         rgb(146,174,47,.5,maxColorValue=255))
         
wisc_pal<-colorFactor(palette=color,domain=wiscland_wilms$GRIDCODE)
label8<-sprintf("<strong> %s</strong>",
                 wiscland_wilms$cls_desc_3)%>% lapply(htmltools::HTML)


label7<-sprintf("<strong> %s</strong>",
                wiscland_wilms_updates$type)%>% lapply(htmltools::HTML)
#subbasin prep
label6<-sprintf("<strong> %s</strong>",
                subbasin$GRIDCODE)%>% lapply(htmltools::HTML)

#impaired streams prep
impair_cols<-c("Blue", 
               "#7D692A",
               "#F12B0C",
               "orange") #brown sediment & P
pal6<-colorFactor(palette=impair_cols, domain=impaired_streams$Pollutant_)
label9<-sprintf("<strong> %s</strong><br/>Pollutant: %s",
                impaired_streams$Label,impaired_streams$Pollutant_)%>% lapply(htmltools::HTML)
pal6<-colorFactor(palette=impair_cols, domain=impaired_streams$Pollutant_)

p = colorFactor(palette =c("Blue","Brown","Red","Orange"),domain= c("Delist","Sediment (TSS)","Phosphorus","Phosphorus & Sediment (TSS)"),ordered= TRUE)

#septic parcel prep
resident_col<-c("#F7580D",
                "#498228")
pal7<-colorFactor(palette=resident_col, domain=septic_parcel$permenent)
p1 = colorFactor(palette =c("#F7580D","#498228"),domain= c("seasonal resident","permanent resident"),ordered= TRUE)

#questions
label12<-sprintf("<strong>Q #: </strong> %s</br><strong>Lake: </strong> %s</br><strong>Q: </strong> %s</br><strong>Who/What: </strong> %s</br>",questions$Name,questions$Lake,questions$question,questions$who_or_wha)%>% lapply(htmltools::HTML)

#impaired lakes prep
label11<-sprintf("<strong>Lake:</strong> %s <br/>
<strong>WBIC:</strong> %s <br/>
<strong>County:</strong> %s <br/>
<strong>9KE_plan:</strong> %s <br/>
<strong>Lake_Type_NR_10206_confirmed_by_MG:</strong> %s <br/>
<strong>Lake_Type_ROW:</strong> %s <br/>
<strong>type_comment:</strong> %s <br/>
<strong>Priority:</strong> %s <br/>
<strong>Stratified:</strong> %s <br/>
<strong>TP_critiera_NR_10206:</strong> %s <br/>
<strong>area_ac:</strong> %s <br/>
<strong>depth_max_ft_ROW :</strong> %s <br/>
<strong>volume_final_ac_ft:</strong> %s <br/>
<strong>volume_source:</strong> %s <br/>
<strong>subbasins_in_SWAT:</strong> %s <br/>
<strong>subbasins_in_SWAT_correct:</strong> %s <br/>
<strong>subbasins_out_SWAT:</strong> %s <br/>
<strong>subbasins_out_SWAT_correct:</strong> %s <br/>
<strong>internally_drained_swat:</strong> %s <br/>
<strong>internally_drained_swat_correct:</strong> %s <br/>
<strong>seasonal_septic:</strong> %s <br/>
<strong>permanent_septic:</strong> %s <br/>
<strong>total_septic:</strong> %s <br/>
<strong>gsm_2015_to_2020:</strong> %s <br/>
<strong>count_2015_to_2020:</strong> %s <br/>
<strong>gsm_all:</strong> %s <br/>
<strong>count_all:</strong> %s <br/>
<strong>min_date_all:</strong> %s <br/>
<strong>max_date_all:</strong> %s",
                impaired_lakes$Lake,
impaired_lakes$WBIC,
impaired_lakes$County,
impaired_lakes$x9KE_plan,
impaired_lakes$Lake_Type_NR_10206_confirmed_by_MG,
impaired_lakes$Lake_Type_ROW,
impaired_lakes$type_comment,
impaired_lakes$Priority,
impaired_lakes$Stratified,
impaired_lakes$TP_critiera_NR_10206,
impaired_lakes$area_ac,
impaired_lakes$depth_max_ft_ROW ,
impaired_lakes$volume_final_ac_ft,
impaired_lakes$volume_source,
impaired_lakes$subbasins_in_SWAT,
impaired_lakes$subbasins_in_SWAT_correct,
impaired_lakes$subbasins_out_SWAT,
impaired_lakes$subbasins_out_SWAT_correct,
impaired_lakes$internally_drained_swat,
impaired_lakes$internally_drained_swat_correct,
impaired_lakes$seasonal_septic,
impaired_lakes$permanent_septic,
impaired_lakes$total_septic,
impaired_lakes$gsm_2015_to_2020,
impaired_lakes$count_2015_to_2020,
impaired_lakes$gsm_all,
impaired_lakes$count_all,
impaired_lakes$min_date_all,
impaired_lakes$max_date_all
)%>% lapply(htmltools::HTML)

#lake additions prep
label10<-sprintf("<strong>Lake:</strong> %s <br/>
<strong>WBIC:</strong> %s <br/>
<strong>County:</strong> %s <br/>
<strong>9KE_plan:</strong> %s <br/>
<strong>Lake_Type_NR_10206_confirmed_by_MG:</strong> %s <br/>
<strong>Lake_Type_ROW:</strong> %s <br/>
<strong>type_comment:</strong> %s <br/>
<strong>Priority:</strong> %s <br/>
<strong>Stratified:</strong> %s <br/>
<strong>TP_critiera_NR_10206:</strong> %s <br/>
<strong>area_ac:</strong> %s <br/>
<strong>depth_max_ft_ROW :</strong> %s <br/>
<strong>volume_final_ac_ft:</strong> %s <br/>
<strong>volume_source:</strong> %s <br/>
<strong>subbasins_in_SWAT:</strong> %s <br/>
<strong>subbasins_in_SWAT_correct:</strong> %s <br/>
<strong>subbasins_out_SWAT:</strong> %s <br/>
<strong>subbasins_out_SWAT_correct:</strong> %s <br/>
<strong>internally_drained_swat:</strong> %s <br/>
<strong>internally_drained_swat_correct:</strong> %s <br/>
<strong>seasonal_septic:</strong> %s <br/>
<strong>permanent_septic:</strong> %s <br/>
<strong>total_septic:</strong> %s <br/>
<strong>gsm_2015_to_2020:</strong> %s <br/>
<strong>count_2015_to_2020:</strong> %s <br/>
<strong>gsm_all:</strong> %s <br/>
<strong>count_all:</strong> %s <br/>
<strong>min_date_all:</strong> %s <br/>
<strong>max_date_all:</strong> %s",
                lake_additions$Lake,
lake_additions$WBIC,
lake_additions$County,
lake_additions$x9KE_plan,
lake_additions$Lake_Type_NR_10206_confirmed_by_MG,
lake_additions$Lake_Type_ROW,
lake_additions$type_comment,
lake_additions$Priority,
lake_additions$Stratified,
lake_additions$TP_critiera_NR_10206,
lake_additions$area_ac,
lake_additions$depth_max_ft_ROW ,
lake_additions$volume_final_ac_ft,
lake_additions$volume_source,
lake_additions$subbasins_in_SWAT,
lake_additions$subbasins_in_SWAT_correct,
lake_additions$subbasins_out_SWAT,
lake_additions$subbasins_out_SWAT_correct,
lake_additions$internally_drained_swat,
lake_additions$internally_drained_swat_correct,
lake_additions$seasonal_septic,
lake_additions$permanent_septic,
lake_additions$total_septic,
lake_additions$gsm_2015_to_2020,
lake_additions$count_2015_to_2020,
lake_additions$gsm_all,
lake_additions$count_all,
lake_additions$min_date_all,
lake_additions$max_date_all
)%>% lapply(htmltools::HTML)


#centers
#impaired lakes
cnt = rgeos::gCentroid(impaired_lakes, byid = TRUE)
crd = data.frame(coordinates(cnt))

#additonal lakes
cnt1 = rgeos::gCentroid(lake_additions, byid = TRUE)
crd1 = data.frame(coordinates(cnt1))

#questions
cnt2 = rgeos::gCentroid(questions, byid = TRUE)
crd2 = data.frame(coordinates(cnt2))


map=leaflet()  %>% 
  addTiles(group = "Street View") %>% 
  addProviderTiles("Esri.WorldTopoMap", group = "Topo") %>%
  addProviderTiles(providers$Esri.WorldImagery, group = "Satellite") %>%
  setView(lng = -87.870196, lat=44.104887,zoom=9) %>% 
  addPolylines(data=county,
               color="grey",
               opacity=0.8,
               group="County")%>%
  addPolylines(data=flow,
               weight=1,
               color="blue",
               opacity = 0.8,
               group="flow, all")%>%
    addPolylines(data=gass_hydro,
               weight=1,
               color="#E424D8",
               opacity = 0.8,
               group="gass hydro")%>%
  addPolylines(data=swat_routing,
               weight=2,
               color="blue",
               opacity = 0.8,
               group="flow, swat routing")%>%
  addPolylines(data=subbasin,
               color="black",
               weight=1,
               opacity=0.8,
               group="subbasin",
               label=label6,
               dashArray = "",
               highlight = highlightOptions(weight = 5,
                                            color = "#666",
                                            
                                            fillOpacity = 0.7,
                                            bringToFront = TRUE),
               labelOptions = labelOptions(style = list("font-weight" = "normal", padding = "3px 8px"),
                                           textsize = "15px",
                                           direction = "auto"))%>%
  addPolylines(data=manitowoc_co_lidar,
               color="#86EF56",
               weight=2,
               opacity=0.8,
               group="Manitowoc Co lidar delineations")%>%
    addPolylines(data=manitowoc_co_lidar_private,
               color="#86EF56",
               weight=2,
               opacity=0.8,
               group="Manitowoc Co lidar delineations 2")%>%
  addPolylines(data=cal_man_9KE,
               color="#F49C5E",
               weight=2,
               opacity=0.8,
               group="Cal-Man 9KE Onterra delineations")%>%
  addPolylines(data=impaired_streams,
               color=~pal6(Pollutant_),
               weight=2,
               opacity = .8,
               label=label9,
               group="2020 Impaired Streams (TP & TSS)",
               dashArray = "",
               highlight = highlightOptions(weight = 5,
                                            color = "#666",
                                            
                                            fillOpacity = 0.7,
                                            bringToFront = TRUE),
               labelOptions = labelOptions(style = list("font-weight" = "normal", padding = "3px 8px"),
                                           textsize = "15px",
                                           direction = "auto"))%>%
  addPolygons(data=impaired_lakes,
              color="red",
              fillOpacity=.4,
              group="2020 Impaired Lakes (TP)",
              popup=label11,
              dashArray = "",
              highlight = highlightOptions(weight = 5,
                                           color = "#666",
                                           
                                           fillOpacity = 0.7,
                                           bringToFront = TRUE),
              labelOptions = labelOptions(style = list("font-weight" = "normal", padding = "3px 8px"),
                                          textsize = "15px",
                                          direction = "auto"))%>%
  addLabelOnlyMarkers(lng = ~ x, lat = ~ y, data = crd,
                     label = impaired_lakes@data$Lake,
                     group="2020 Impaired Lakes (TP)",
                     labelOptions = labelOptions(noHide = TRUE,
                                                   textOnly = TRUE,
                                                 style=list('color'="#842020",'font-size'="14px","font-weight" = "bold"))) %>%

    addPolygons(data=lake_additions,
              color="orange",
              fillOpacity=.4,
              group="Lake Additions MG",
              popup=label10,
              dashArray = "",
              highlight = highlightOptions(weight = 5,
                                           color = "#666",
                                           
                                           fillOpacity = 0.7,
                                           bringToFront = TRUE),
              labelOptions = labelOptions(style = list("font-weight" = "normal", padding = "3px 8px"),
                                          textsize = "15px",
                                          direction = "auto"))%>%
    addLabelOnlyMarkers(lng = ~ x, lat = ~ y, data = crd1,
                     label = lake_additions@data$Lake,
                     group="Lake Additions MG",
                     labelOptions = labelOptions(noHide = TRUE,
                                                   textOnly = TRUE,
                                                 style=list('color'="#A18733",'font-size'="14px"))) %>%
  addPolylines(data=buffer,
               color="#F45EDE",
               weight=2,
               opacity=0.8,
               group="lakes buffer, 500ft")%>%
  addPolylines(data=septic_parcel,
               color=~pal7(permenent),
               weight=2,
               opacity=0.8,
               group="septic parcels")%>%
  addCircleMarkers(data=septic_pts,
               radius = 5,
               color=~pal7(permenent),
               weight=2,
               opacity=0.8,
               group="septic points")%>%
    addCircleMarkers(data=questions,
               radius = 10,
               color="blue",
               weight=2,
               opacity=0.8,
               popup=label12,
               group="questions")%>%
    addLabelOnlyMarkers(lng = ~ x, lat = ~ y, data = crd2,
                      label =questions@data$Name,
                      group="questions",
                      labelOptions = labelOptions(noHide = TRUE,
                      style=list('color'="black",'font-size'="14px")))%>%
  
  addPolygons(data=wiscland_wilms,
              color=~wisc_pal(GRIDCODE),
              fillOpacity=.5,
              group="wiscland2",
              label=label8,
              dashArray = "",
              highlight = highlightOptions(weight = 1,
                                           color = "#666",
                                           
                                           fillOpacity = 0.7,
                                           bringToFront = TRUE),
              labelOptions = labelOptions(style = list("font-weight" = "normal", padding = "3px 8px"),
                                          textsize = "15px",
                                          direction = "auto"))%>%
  addPolygons(data=wiscland_wilms_updates,
              color="grey",
              fillOpacity=.5,
              group="wiscland2 KO updates",
              label=label7,
              dashArray = "",
              highlight = highlightOptions(weight = 1,
                                           color = "#666",
                                           
                                           fillOpacity = 0.7,
                                           bringToFront = TRUE),
              labelOptions = labelOptions(style = list("font-weight" = "normal", padding = "3px 8px"),
                                          textsize = "15px",
                                          direction = "auto"))%>%
  

  addLegend("bottomleft", pal=p, values=c("Delist","Sediment (TSS)","Phosphorus","Phosphorus & Sediment (TSS)"), title="2020 impaired streams",group="2020 Impaired Streams (TP & TSS)")%>%
  addLegend("bottomleft", pal=p1, values=c("seasonal resident","permanent resident"), title="Septic Residency",group="septic points")%>%
  addLayersControl(baseGroups = c("Street View", "Satellite","Topo"),
                   overlayGroups=c("subbasin","County","flow, all","flow, swat routing","gass hydro","2020 Impaired Streams (TP & TSS)","2020 Impaired Lakes (TP)","Manitowoc Co lidar delineations","Manitowoc Co lidar delineations 2","Cal-Man 9KE Onterra delineations" , "lakes buffer, 500ft","septic parcels","septic points","wiscland2","wiscland2 KO updates","Lake Additions MG","questions"),options = layersControlOptions(collapsed = FALSE))%>%
  hideGroup(c("wiscland2","flow, all", "lakes buffer, 500ft","septic parcels","septic points"))
  map


```
